version: "3.8"

services:
  db:
    image: "postgres-tegon:latest"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - tegon
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:latest
    depends_on:
      - db
    environment:
      POSTGRESQL_CONNECTION_URI: ${SUPERTOKEN_DATABASE_URL}
    ports:
      - 3567:3567
    networks:
      - tegon
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
  tegon: {}

volumes:
  postgres-data:
